// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartParking.API.Models;

#nullable disable

namespace SmartParking.API.Migrations
{
    [DbContext(typeof(ParkingContext))]
    [Migration("20251227001725_AdicionarUsers")]
    partial class AdicionarUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartParking.API.Models.Lugar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NumeroLugar")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ParqueId")
                        .HasColumnType("int");

                    b.Property<int>("Piso")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Lugares__3214EC07CFEAEF07");

                    b.HasIndex("ParqueId");

                    b.ToTable("Lugares");
                });

            modelBuilder.Entity("SmartParking.API.Models.Parque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadeTotal")
                        .HasColumnType("int");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Parques__3214EC0786113281");

                    b.ToTable("Parques");
                });

            modelBuilder.Entity("SmartParking.API.Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("LugarId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Presenca");

                    b.Property<DateTime?>("UltimaAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Sensores__3214EC07A6A98226");

                    b.HasIndex(new[] { "LugarId" }, "UQ__Sensores__1BDE0DE16490C0D1")
                        .IsUnique();

                    b.ToTable("Sensores");
                });

            modelBuilder.Entity("SmartParking.API.Models.Lugar", b =>
                {
                    b.HasOne("SmartParking.API.Models.Parque", "Parque")
                        .WithMany("Lugares")
                        .HasForeignKey("ParqueId")
                        .IsRequired()
                        .HasConstraintName("FK_Lugares_Parques");

                    b.Navigation("Parque");
                });

            modelBuilder.Entity("SmartParking.API.Models.Sensor", b =>
                {
                    b.HasOne("SmartParking.API.Models.Lugar", "Lugar")
                        .WithOne("Sensor")
                        .HasForeignKey("SmartParking.API.Models.Sensor", "LugarId")
                        .IsRequired()
                        .HasConstraintName("FK_Sensores_Lugares");

                    b.Navigation("Lugar");
                });

            modelBuilder.Entity("SmartParking.API.Models.Lugar", b =>
                {
                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SmartParking.API.Models.Parque", b =>
                {
                    b.Navigation("Lugares");
                });
#pragma warning restore 612, 618
        }
    }
}
